// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type IdPathReq struct {
	Id string `path:"id,omitempty"`
}

type User struct {
	Id       string `json:"id,omitempty"`
	Password string `json:"password,omitempty"`
	Name     string `json:"name,omitempty"`
	Status   int    `json:"status,omitempty"`
}

type LoginReq struct {
	Name     string `json:"name,omitempty"`
	Password string `json:"password,omitempty"`
}

type LoginResp struct {
	Status       int    `json:"status,omitempty"`
	Id           string `json:"id,omitempty"`
	Name         string `json:"name,omitempty"`
	AccessToken  string `json:"token,omitempty"`
	AccessExpire int64  `json:"accessExpire,omitempty"`
	RefreshAfter int64  `json:"refreshAfter,omitempty"`
}

type UpPasswordReq struct {
	Id     string `json:"id"`
	OldPwd string `json:"oldPwd"`
	NewPwd string `json:"newPwd"`
}

type UserListReq struct {
	Ids   []string `json:"ids,omitempty"`
	Name  string   `json:"name,omitempty"`
	Page  int      `json:"page,omitempty"`
	Count int      `json:"count,omitempty"`
}

type UserListResp struct {
	Count int64   `json:"count"`
	List  []*User `json:"data"`
}
