// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	v1user "cheddar/internal/handler/v1/user"
	"cheddar/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Jwt},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: v1user.CreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: v1user.EditHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: v1user.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: v1user.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: v1user.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: v1user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/password",
					Handler: v1user.UpPasswordHandler(serverCtx),
				},
			}...,
		),
	)
}
